version: '2'
services:
  gnsgschoolapp-app:
    image: gnsgschoolapp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://gnsgschoolapp-mysql:3306/gnsgschoolapp?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://gnsgschoolapp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://gnsgschoolapp-elasticsearch:9200
    ports:
      - 8080:8080
  gnsgschoolapp-mysql:
    extends:
      file: mysql.yml
      service: gnsgschoolapp-mysql
  gnsgschoolapp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: gnsgschoolapp-elasticsearch
